export { default as Dashboard } from "./Dashboard";
export { default as Home } from "./Home";
export { default as Users } from "./Users";
export { default as Products } from "./Prouducts";
export { default as Manage } from "./Manage";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Error404 } from "./404";
export { default as Unauthorized } from "./Unauthorized";
